import { ArrowRight, Baby, PersonStanding, Phone, Sparkles, Target, type LucideIcon } from "lucide-react";
import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { SectionHeading } from "./section-heading";

const icons: LucideIcon[] = [Baby, PersonStanding, Target, Sparkles];
const guidance = ["Age and stage", "Water confidence", "Current ability", "Swimming goals"];

export async function Lessons() {
  const supabase = await createSupabaseServerClient();
  const result = supabase ? await supabase.from("lesson_types").select("*").eq("active", true).order("display_order").limit(4) : { data: null };
  const lessons = result.data ?? [];
  return <section id="lessons" className="py-24 sm:py-32"><div className="container-site"><SectionHeading eyebrow="LESSONS FOR EVERY SWIMMER" title="Find the right lesson" copy="Browse active MYMZ lessons when available, or tell us about the swimmer for personal guidance." />{lessons.length ? <div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{lessons.map((lesson, i) => { const Icon = icons[i % icons.length]; return <article key={lesson.id} className="group flex min-h-[22rem] flex-col rounded-[1.75rem] border border-navy/8 bg-white p-7 shadow-[0_14px_45px_rgba(6,27,44,.06)] transition duration-500 hover:-translate-y-2 hover:border-aqua/60 hover:shadow-[0_22px_60px_rgba(6,27,44,.1)]"><span className="grid size-14 place-items-center rounded-2xl bg-cream text-ocean transition group-hover:bg-navy group-hover:text-aqua"><Icon className="size-6" /></span><span className="mt-10 text-xs font-bold tracking-[.14em] text-ocean">{String(i + 1).padStart(2, "0")}</span><h3 className="display mt-3 text-2xl font-bold text-navy">{lesson.name}</h3><p className="mt-4 flex-1 text-sm leading-7 text-slate-600">{lesson.description}</p><Link href={`/book?lesson=${lesson.slug}`} className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-bold text-navy transition group-hover:text-ocean">View lesson <ArrowRight className="size-4" /></Link></article>; })}</div> : <div className="mt-12 overflow-hidden rounded-[2.25rem] bg-navy text-white shadow-[0_22px_70px_rgba(6,27,44,.14)]"><div className="grid gap-10 p-7 sm:p-10 lg:grid-cols-[1.1fr_.9fr] lg:p-12"><div><p className="eyebrow !text-aqua">PERSONAL LESSON GUIDANCE</p><h3 className="display mt-4 text-3xl font-bold sm:text-4xl">Not sure which lesson is right?</h3><p className="mt-5 max-w-xl leading-8 text-white/65">Tell us a little about the swimmer and MYMZ will help you explore the most suitable option without guessing.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/enquire" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-aqua px-6 text-xs font-extrabold tracking-[.1em] text-navy transition hover:bg-white">FIND THE RIGHT LESSON <ArrowRight className="size-4" /></Link><a href="tel:07383488189" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-white/20 px-6 text-xs font-extrabold tracking-[.1em] text-white transition hover:border-aqua hover:text-aqua"><Phone className="size-4" />CALL 07383 488189</a></div></div><ul className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{guidance.map(item => <li key={item} className="flex items-center gap-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm font-semibold text-white/80"><span className="grid size-7 place-items-center rounded-full bg-aqua/15 text-aqua"><Sparkles className="size-3.5" /></span>{item}</li>)}</ul></div></div>}</div></section>;
}
